### ISSUE TITLE
ERROR: Error while pulling image

### ISSUE THREAD

**Issue by nainav** [fabric8-analytics/fabric8-analytics-common#23] opened 2017-06-06 11:22 UTC
ERROR: Error while pulling image: Get
http://docker-registry.usersys.redhat.com/v1/repositories/bayesian/cvedb-s3-dump/images: dial tcp: lookup
docker-registry.usersys.redhat.com on 10.16.36.29:53: no such host

logs : https://gist.github.com/naina-verma/4f13edb544080a78537ab5bbb30b7df7

**Comment by nainav** [comment] 2017-06-06 11:23
Workaround for this is(temporary) :

    

- Go to docker-compose.yml inside  fabric8-analytics-common
- comment out 286 till 298 line https://github.com/fabric8-analytics/fabric8-analytics-common/blob/master/docker-compose.yml#L286

Note: the cvedb-s3-dum will not be working after this !

**Comment by tisnik** [comment] 2017-06-06 15:11
Hi @naina-verma. It was temporary issue fixed by @vpavlin by restarting the server (thanks a lot!).

**Comment by naina-verma** [comment] 2017-06-06 15:24
@vpavlin , can you please link me to the fix in terms of PR!

**Comment by vpavlin** [comment] 2017-06-06 18:12
No, I cannot. The server where the registry runs got shutdown for some reason, so I just started it. I think proper issue and fix to this situation would something like: "Migrate images from docker-registry.usersys.redhat.com"

Reasoning:
* The registry is maintained by vpavlin, thus unsupported
* It's running on OS1 (OpenStack instance managed by PnT DevOps) which is going to be decommissioned soon-ish
* There is a supported registry now (which I cannot find link to at the moment, but can look at it tomorrow)

**Comment by fridex** [comment] 2017-06-13 14:49
I believe we can close this as this is not a bug that would be related to this code-base. If such occurs, please reach out to @vpavlin who will help. Hopefully we will soon move to another registry. Thanks!

**Closed by fridex** 2017-06-13 14:49 UTC
